# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*

pr: 
- develop
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "triggered by dev"
    echo $(Build.SourceBranch)
  displayName: 'Run a one-line script'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')

- script: |
    echo "triggered by master"
    echo $(Build.SourceBranch)
  displayName: 'Run a one-line script'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')

- script: |
    echo "triggered by feature"
    echo $(Build.SourceBranch)
  displayName: 'Run a one-line script'
  condition: contains(variables['build.sourceBranch'], 'feature')

- script: |
    echo "triggered by pr"
    echo "source branch is $(System.PullRequest.SourceBranch)"
    echo "target branch is $(System.PullRequest.TargetBranch)"
  displayName: 'lalala'
  condition: and(eq(variables['Build.Reason'], 'PullRequest'), contains(variables['System.PullRequest.TargetBranch'], 'develop'))